name: Create Release

on:
  push:
    tags:
      - "v*" # Triggers on version tags like v1.0.0, v1.2.3, etc.

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Update manifest version
        run: |
          VERSION_NUMBER=$(echo "${{ steps.get_version.outputs.VERSION }}" | sed 's/^v//')
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION_NUMBER\"/" manifest.json
          echo "Updated manifest.json version to $VERSION_NUMBER"

      - name: Create XPI package
        run: |
          # Create the XPI file (which is just a ZIP with .xpi extension)
          zip -r paperless-uploader-${{ steps.get_version.outputs.VERSION }}.xpi \
            manifest.json \
            background.js \
            popup.html \
            popup.js \
            options.html \
            options.js \
            upload-dialog.html \
            upload-dialog.js \
            create-correspondent.html \
            create-correspondent.js \
            create-document-type.html \
            create-document-type.js \
            fuse.min.js \
            utils.js \
            icons/ \
            -x "*.git*" "*.github*" "README.md" "LICENSE" "assets/" "package.json"

          # Verify the XPI was created
          ls -la *.xpi

      - name: Generate Release Notes
        id: generate_notes
        run: |
          cat > release_notes.md << 'EOF'
          ## What's New in ${{ steps.get_version.outputs.VERSION }}

          ### 🚀 Features
          - Upload PDF attachments directly to Paperless-ngx from Thunderbird
          - Create new correspondents and document types on-the-fly
          - Configurable settings for Paperless-ngx server connection
          - Context menu integration for easy access
          - Automatic document metadata extraction from emails

          ### 📥 Installation
          #### Thunderbird Add-On Gallery
          - Just search for the Add-On in Thunderbird and install it like any other Add-On
          #### Manual
          1. Download the `paperless-uploader-${{ steps.get_version.outputs.VERSION }}.xpi` file below. If you use Firefox, make sure to right-click and save the XPI file, not just clicking it (`Save target as...`)
          2. In Thunderbird, go to **Add-ons and Themes** > **Extensions** > **Install Add-on From File...**
          3. Select the downloaded `.xpi` file and follow the prompts
          4. Configure your Paperless-ngx server URL and API key in the extension preferences
          

          ### 🔧 Requirements
          - Thunderbird 140.0 or later
          - Paperless-ngx server with API access
          - Valid API token for your Paperless-ngx instance
          EOF

          echo "Generated release notes"

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.get_version.outputs.VERSION }} \
            --title "Paperless Uploader ${{ steps.get_version.outputs.VERSION }}" \
            --notes-file release_notes.md \
            ./paperless-uploader-${{ steps.get_version.outputs.VERSION }}.xpi
